'use babel';

export default class WeatherTables {}

WeatherTables.WeatherDescr = {
   '-1' : '',
    '0' : 'Sunny Day',
    '2' : 'Partly Cloudy',
    '3' : 'Partly Cloudy',
    '5' : 'Mist',
    '6' : 'Fog',
    '7' : 'Cloudy',
    '8' : 'Overcast',
    '9' : 'Light Rain Shower',
   '10' : 'Light Rain Shower',
   '11' : 'Drizzle',
   '12' : 'Light Rain',
   '13' : 'Heavy Rain Shower',
   '14' : 'Heavy Rain Shower',
   '15' : 'Heavy Rain',
   '16' : 'Sleet Shower',
   '17' : 'Sleet Shower',
   '18' : 'Sleet',
   '19' : 'Hail Shower',
   '20' : 'Hail Shower',
   '21' : 'Hail',
   '22' : 'Light Snow Shower',
   '23' : 'Light Snow Shower',
   '24' : 'Light Snow',
   '25' : 'Heavy Snow Shower',
   '26' : 'Heavy Snow Shower',
   '27' : 'Heavy Snow',
   '28' : 'Thunder Shower',
   '29' : 'Thunder Shower',
   '30' : 'Thunder'
};

// https://erikflowers.github.io/weather-icons/
WeatherTables.WeatherIcons = {
  '-1' : '',
   '0' : 'wi-day-sunny',
   '2' : 'wi-night-alt-cloudy',
   '3' : 'wi-day-cloudy',
   '5' : 'wi-day-haze',
   '6' : 'wi-day-fog',
   '7' : 'wi-day-cloudy-high',
   '8' : 'wi-day-sunny-overcast',
   '9' : 'wi-night-alt-rain-mix',
  '10' : 'wi-day-rain-mix',
  '11' : 'wi-day-sprinkle',
  '12' : 'wi-day-showers',
  '13' : 'wi-night-alt-rain',
  '14' : 'wi-day-rain',
  '15' : 'wi-day-rain',
  '16' : 'wi-night-alt-sleet-storm',
  '17' : 'wi-day-sleet-storm',
  '18' : 'wi-day-sleet',
  '19' : 'wi-night-alt-hail',
  '20' : 'wi-day-hail',
  '21' : 'wi-day-hail',
  '22' : 'wi-night-alt-snow',
  '23' : 'wi-day-snow',
  '24' : 'wi-day-snow',
  '25' : 'wi-night-alt-snow-thunderstorm',
  '26' : 'wi-day-snow-thunderstorm',
  '27' : 'wi-day-snow-thunderstorm',
  '28' : 'wi-night-alt-storm-showers',
  '29' : 'wi-day-storm-showers',
  '30' : 'wi-day-thunderstorm'
};
